### ISSUE TITLE
《如何阅读医学论文》、《设计质性研究》这两本书无法获取生成Markdown笔记

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [LumosLovegood/myScripts#1]
用的是[DoubanAllInOne](https://github.com/LumosLovegood/myScripts/tree/main/DoubanAllInOne)这个文件夹里的脚本。

1. 《如何获取医学论文》在quickadd列表中能出现有这本书，点按后在Obsidian右上角弹窗提示“没有作者简介”，然后就没有然后了。

2. 《设计质性研究》 点按后无事发生。

3. 《领悟方法》这本书，能获取生成Markdown笔记，但是Yaml有问题，显示“invalid yaml”

**Comment by LumosLovegood** [comment]
感谢反馈！
现在已经修复了，可以下载最新脚本替换，或者在脚本代码页复制代码粘贴到原来的脚本文件中替换
**并且需要重新把quickadd中的生成命令重启**（就是把闪电⚡图标点灭再点亮一次）

前两本书出现问题原因是之前没有处理好**书籍没有摘录信息的情况**。
《领悟方法》这本书出现问题的原因是书原作名和作者名中出现了特殊字符。
以上两个问题都做了解决。
有什么问题欢迎继续反馈！ []~(￣▽￣)~*🍻
