### ISSUE TITLE
可以添加书籍目录吗？

### ISSUE THREAD

**Issue by kiwiflydream** [LumosLovegood/myScripts#3]
你好，脚本很棒，极大的提高效率，如果可以添加目录就更好了，因为不少笔记是按目录章节记录的，不过豆瓣的话，目录有些书有目录有些书没有， 以  [文学课 (豆瓣)](https://book.douban.com/subject/35643306/?icn=index-latestbook-subject)  为例,目录是这样的

![CleanShot 2022-04-02 at 09 09 16](https://user-images.githubusercontent.com/13311001/161358338-3822be5d-4b2a-4499-aff0-e019b071fd41.png)

**Comment by LumosLovegood** [comment]
可以加目录的，不过如你所说，有些书豆瓣上没有目录信息，所以只能获取部分图书信息的目录。

以及，目录希望以什么样的形式呈现呢？是以纯文本？有序或无序列表？还是以标题形式呈现呢？

🥂

**Comment by kiwiflydream** [comment]
🤝  感谢回复，目测豆瓣冷门或新书的话目录应该没有，这个有就添加，没有就空着应该问题不大。目录最好是标题形式，但是感觉不好处理。因为豆瓣的目录是没有结构并且混乱的。比如这本 [演讲的逻辑 (豆瓣)](https://book.douban.com/subject/35763457/?icn=index-latestbook-subject)  

![CleanShot 2022-04-02 at 11 19 10](https://user-images.githubusercontent.com/13311001/161363916-164c131f-cea1-4fb5-9282-799c4bcb04f8.png)

它的大章节跟下面小章节是不太好区分的，不是 h1、h2 这样，全部是纯文本有的还带页数，所以直接生成标题很难。

就我个人而言，生成纯文本就够了，后续再手动调整，不过，这也节省了大量时间。

**Comment by LumosLovegood** [comment]
好滴，那就先以纯文本的形式呈现，确实不同书的很多字段的用的格式不一样，如果之后遇到部分书的输出内容有问题可以再反馈的。

中午看一下时间，最迟晚上可以增加目录信息🌕

🍺

**Comment by LumosLovegood** [comment]
已增加目录信息✔️ 可以通过 **{{VALUE:catalog}}** 使用

**Comment by kiwiflydream** [comment]
> 已增加目录信息✔️ 可以通过 **{{VALUE:catalog}}** 使用

感谢大佬，已经用上，特别好用，理想中的工作流，强 👍
